spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - Weight=group1,product-service-19093,7 # 70% 확률로 19093에 요청
            - Weight=group1,product-service-19094,3 # 30% 확률로 19094에 요청
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
      discovery:
        locator:
          enabled: true
server:
  port: 19091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
service:
  jwt:
    access-expiration: 3600000
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
